# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    info:
      title: Todo List API
      description: A comprehensive API for managing tasks and subtasks, built with Symfony.
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
  areas:
    path_patterns:
      - ^/api(?!/doc$) # Document all routes under /api, except the doc route itself
