services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: todo_list_php
    volumes:
      - ./:/var/www/html
    networks:
      - todo_list_network

  nginx:
    image: nginx:alpine
    container_name: todo_list_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - todo_list_network

  mysql:
    image: mysql:8.0
    container_name: todo_list_mysql
    restart: always
    environment:
      MYSQL_DATABASE: todo_list_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_list_network

networks:
  todo_list_network:
    driver: bridge

volumes:
  mysql_data: